language: php

services:
  - mysql

jobs:
  fast_finish: true
  include:
    - env: DBTYPE=mysql; MW=1.34.0
      php: 7.3

install:
  - travis_retry composer self-update
  - bash .travis.install.sh

script:
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Network/phpunit.xml.dist
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]] ; then cd ../phase3/extensions/Network/ && make ci ; fi

cache:
  directories:
    - $HOME/.composer/cache
