name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_33'
            php: 7.3
          - mw: 'REL1_34'
            php: 7.4
          - mw: 'master'
            php: 7.4

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v2
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - name: Download MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: |
          wget https://github.com/wikimedia/mediawiki/archive/${{ matrix.mw }}.tar.gz -nv
          tar -zxf ${{ matrix.mw }}.tar.gz
          mv mediawiki-${{ matrix.mw }} mediawiki

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        run: |
          composer install
          php maintenance/install.php --dbtype sqlite --dbuser root --dbname mw --dbpath $(pwd) --pass AdminPass10 WikiName AdminUser

      - name: Create composer.local.json
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        run: |
          cat <<EOT >> composer.local.json
          {
          	"extra": {
          		"merge-plugin": {
          			"merge-dev": true,
          			"include": [
          				"extensions/Network/composer.json"
          			]
          		}
          	}
          }
          EOT

      - name: Update LocalSetting.php
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        run: |
          tail -n5 LocalSettings.php
          echo 'error_reporting(E_ALL| E_STRICT);' >> LocalSettings.php
          echo 'ini_set("display_errors", 1);' >> LocalSettings.php
          echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
          echo '$wgShowDBErrorBacktrace = true;' >> LocalSettings.php
          echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php
          echo 'wfLoadExtension( "Network" );' >> LocalSettings.php

      - uses: actions/checkout@v2
        with:
          path: mediawiki/extensions/Network

      - name: Composer update
        run: composer update

      - name: Run PHPUnit
        run: php tests/phpunit/phpunit.php -c extensions/Network/phpunit.xml.dist

  coding-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
          tools: composer, cs2pr

      - name: composer install
        run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader"

      - name: phpcs
        run: "php vendor/bin/phpcs -q --report=checkstyle --no-colors | cs2pr"

  static-analysis:
    name: "Static Analysis"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
          tools: composer, cs2pr

      - name: composer install
        run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader"

      - name: phpstan
        run: "php vendor/bin/phpstan analyse --error-format=checkstyle --no-progress | cs2pr"
